name: uyum_package
description: Uyum Mobile Package Exemple Project
version: 1.0.0
homepage: https://github.com/Sd37289/GitHub_Exemple/tree/main/uyum_package
#aurhor: Uyum Mobile  <sd37289@gmail.com>

environment:
  sdk: '>=3.2.0-231.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
